### ISSUE TITLE
Directions say file should be name .z64, but games only boot when its named .v64

### ISSUE THREAD

**Issue by manichispanic999** [fhoedemakers/smsplus64#7]
the directions say to name the file to gen.z64 but i get an error saying it can't find the emulator. once i renamed the file gen.v64 (like all the other emulators are named) it boots the game gear and master system games.

**Comment by fhoedemakers** [comment]
Ok, thanks. I'll update the docs

**Comment by fhoedemakers** [comment]
Updated README and CHANGELOG
